name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  lint-build-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Pylint (fail if score < 9.0)
      run: |
        SCORE=$(pylint app | tee pylint.log | tail -n 2 | head -n 1 | grep -o '[0-9.]\{1,\}' | head -1)
        echo "Pylint Score: $SCORE"
        MIN_SCORE=9.0
        if (( $(echo "$SCORE < $MIN_SCORE" | bc -l) )); then
          echo "❌ Pylint score too low: $SCORE"
          exit 1
        else
          echo "✅ Pylint passed with score: $SCORE"
        fi

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/object-detection-api:latest
