name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  lint-build-push:
    runs-on: self-hosted

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Pylint (fail if score < 9.0)
      run: |
        SCORE=$(pylint app | tee pylint.log | tail -n 2 | head -n 1 | grep -o '[0-9.]\{1,\}' | head -1)
        echo "Pylint Score: $SCORE"
        MIN_SCORE=9.0
        if (( $(echo "$SCORE < $MIN_SCORE" | bc -l) )); then
          echo "❌ Pylint score too low: $SCORE"
          exit 1
        else
          echo "✅ Pylint passed with score: $SCORE"
        fi

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/object-detection-api:latest

    - name: Deploy to Proxmox VM
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        script: |
          docker stop object-api || true
          docker rm object-api || true
          docker pull ${{ secrets.DOCKER_USERNAME }}/object-detection-api:latest
          docker run -d --name object-api -p 8000:8000 ${{ secrets.DOCKER_USERNAME }}/object-detection-api:latest
